### ISSUE TITLE
NabigationBarでの画面遷移を実現

### ISSUE THREAD

**Issue by O-Junpei** [O-Junpei/SCP-ReportViewer#1]

**Comment by O-Junpei** [comment]
TabBarControllerの下にNavigationControllerを設置してみよう。

参考サイト
https://swiswiswift.com/2018/06/03/uitabbarcontroller-and-uinavigationcontroller/

**Comment by O-Junpei** [comment]
NavigationControllerについて、ちょっと調べたことをここにかるーく書いてみてください！

**Comment by InotinoUdon** [comment]
・上部にナビゲーションバーを表示し、複数画面を階層的に行ったり来たりできるようにするヘッダーみたいな部品（クラス）のこと
・こいつ自身は画面のレイアウトを持ってない
・NavigationControllerは複数のUIViewControllerたちの親のようなものであり、それらの推移情報を管理している

**Comment by O-Junpei** [comment]
説明もいい感じですね！
あとUIViewControllerとNavigationControllerのクラス的な親子関係も押さえておいてください！
